In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
df=pd.read_csv('spgclasstry.csv')
df.head()

temperature_2_m_above_gnd  relative_humidity_2_m_above_gnd  \
0                       2.17                               31   
1                       2.31                               27   
2                       3.65                               33   
3                       5.82                               30   
4                       7.73                               27   

   mean_sea_level_pressure_MSL  total_cloud_cover_sfc  \
0                       1035.0                    0.0   
1                       1035.1                    0.0   
2                       1035.4                    0.0   
3                       1035.4                    0.0   
4                       1034.4                    0.0   

   medium_cloud_cover_mid_cld_lay  low_cloud_cover_low_cld_lay  \
0                               0                            0   
1                               0                            0   
2                               0                            0   
3                               0                            0   
4                               0                            0   

   shortwave_radiation_backwards_sfc  wind_speed_10_m_above_gnd  \
0                               0.00                       6.37   
1                               1.78                       5.15   
2                             108.58                       4.68   
3                             258.10                       3.60   
4                             375.58                       6.21   

   wind_gust_10_m_above_gnd  angle_of_incidence     zenith    azimuth  \
0                     24.48           58.753108  83.237322  128.33543   
1                     21.96           45.408585  75.143041  139.65530   
2                     14.04           32.848282  68.820648  152.53769   
3                     19.80           22.699288  64.883536  166.90159   
4                     16.56           19.199908  63.795208  182.13526   

   Classification  
0               6  
1               4  
2               2  
3               1  
4               1

In [21]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df1 = pd.DataFrame(scaler.fit_transform(df),index=df.index,columns=df.columns)

In [22]:
print(df1['Classification'].unique())

[1.  0.6 0.2 0.  0.8 0.4]


In [41]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
label_encoder=preprocessing.LabelEncoder()
df1['Classification']=label_encoder.fit_transform(df1['Classification'])

In [33]:

Y = df1.iloc[:,-1].values
X = df1.iloc[:,:-1].values

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 40)

In [35]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [42]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB()

In [43]:
Y_pred = classifier.predict(X_test)

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(Y_test,Y_pred)
cm = confusion_matrix(Y_test, Y_pred)

In [45]:
print(ac)

0.4863582443653618


In [46]:
print(cm)

[[ 64  15   0   0   5   1]
 [ 23  84   6   3  13   8]
 [  9  31  14  14  13  16]
 [  4  26   6   7  11  39]
 [  8  14   4  26  17  47]
 [  6  11   5  39  30 224]]
